export const RESERVATION_FORM_ACTION_ADD = 'Add Reservation';

export const RESERVATION_FORM_ACTION_EDIT = 'Update Reservation';

export const GET_RESERVATIONS_REQUEST = 'GET_RESERVATION_REQUEST';

export const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATION_SUCCESS';

export const GET_RESERVATIONS_FAIL = 'GET_RESERVATION_FAIL';

export const ADD_RESERVATION_REQUEST = 'ADD_RESERVATION_REQUEST';

export const ADD_RESERVATION_SUCCESS = 'ADD_RESERVATION_SUCCESS';

export const ADD_RESERVATION_FAIL = 'ADD_RESERVATION_FAIL';

export const GET_RESERVATION_BY_ID_REQUEST = 'GET_RESERVATION_BY_ID_REQUEST';

export const GET_RESERVATION_BY_ID_SUCCESS = 'GET_RESERVATION_BY_ID_SUCCESS';

export const GET_RESERVATION_BY_ID_FAIL = 'GET_RESERVATION_BY_ID_FAIL';

export const UPDATE_RESERVATION_REQUEST = 'UPDATE_RESERVATION_REQUEST';

export const UPDATE_RESERVATION_SUCCESS = 'UPDATE_RESERVATION_SUCCESS';

export const UPDATE_RESERVATION_FAIL = 'UPDATE_RESERVATION_FAIL';